module.exports = [
  {
    key: "az-Latn-AZ",
    href: "az/",
    title: "Azerbaijani (Latin, Azerbaijan)",
    shortKey: "az",
  },
  {
    key: "bg-BG",
    href: "bg/",
    title: "Bulgarian (Bulgaria)",
    shortKey: "bg",
  },
  {
    key: "zh-CN",
    href: "zh/",
    title: "Chinese (Simplified, PRC)",
    shortKey: "zh",
  },
  {
    key: "cs-CZ",
    href: "cs/",
    title: "Czech (Czech Republic)",
    shortKey: "cs",
  },
  {
    key: "nl-NL",
    href: "nl/",
    title: "Dutch (Netherlands)",
    shortKey: "nl",
  },
  {
    key: "en-GB",
    href: "en-GB/",
    title: "English (United Kingdom)",
    shortKey: "en-GB",
  },
  {
    key: "en-US",
    href: "",
    title: "English (United States)",
    shortKey: "en",
  },
  {
    key: "fi-FI",
    href: "fi/",
    title: "Finnish (Finland)",
    shortKey: "fi",
  },
  {
    key: "fr-FR",
    href: "fr/",
    title: "French (France)",
    shortKey: "fr",
  },
  {
    key: "de-DE",
    href: "de/",
    title: "German (Germany)",
    shortKey: "de",
  },
  {
    key: "de-CH",
    href: "de-CH/",
    title: "German (Switzerland)",
    shortKey: "de-CH",
  },
  {
    key: "el-GR",
    href: "el/",
    title: "Greek (Greece)",
    shortKey: "el",
  },
  {
    key: "it-IT",
    href: "it/",
    title: "Italian (Italy)",
    shortKey: "it",
  },
  {
    key: "ja-JP",
    href: "ja/",
    title: "Japanese (Japan)",
    shortKey: "ja",
  },
  {
    key: "ko-KR",
    href: "ko/",
    title: "Korean (Korea)",
    shortKey: "ko",
  },
  {
    key: "lv-LV",
    href: "lv/",
    title: "Latvian (Latvia)",
    shortKey: "lv",
  },
  {
    key: "pl-PL",
    href: "pl/",
    title: "Polish (Poland)",
    shortKey: "pl",
  },
  {
    key: "pt-BR",
    href: "pt-BR/",
    title: "Portuguese (Brazil)",
    shortKey: "pt-BR",
  },
  {
    key: "pt-PT",
    href: "pt/",
    title: "Portuguese (Portugal)",
    shortKey: "pt",
  },
  {
    key: "ru-RU",
    href: "ru/",
    title: "Russian (Russia)",
    shortKey: "ru",
  },
  {
    key: "sk-SK",
    href: "sk/",
    title: "Slovak (Slovakia)",
    shortKey: "sk",
  },
  {
    key: "sl-SI",
    href: "sl/",
    title: "Slovenian (Slovenia)",
    shortKey: "sl",
  },
  {
    key: "es-MX",
    href: "es-MX/",
    title: "Spanish (Mexico)",
    shortKey: "es-MX",
  },
  {
    key: "es-ES",
    href: "es/",
    title: "Spanish (Spain)",
    shortKey: "es",
  },
  {
    key: "tr-TR",
    href: "tr/",
    title: "Turkish (Turkey)",
    shortKey: "tr",
  },
  {
    key: "uk-UA",
    href: "uk/",
    title: "Ukrainian (Ukraine)",
    shortKey: "uk",
  },
  {
    key: "vi-VN",
    href: "vi/",
    title: "Vietnamese (Vietnam)",
    shortKey: "vi",
  },
];
