module.exports = [
  {
    key: "az-Latn-AZ",
    href: "/az/",
    title: "Azerbaijani (Latin, Azerbaijan)",
    shortKey: "az",
    name: "az.flag",
  },
  {
    key: "bg-BG",
    href: "/bg/",
    title: "Bulgarian (Bulgaria)",
    shortKey: "bg",
    name: "bg.flag",
  },
  {
    key: "zh-CN",
    href: "/zh/",
    title: "Chinese (Simplified, PRC)",
    shortKey: "zh",
    name: "zh.flag",
  },
  {
    key: "cs-CZ",
    href: "/cs/",
    title: "Czech (Czech Republic)",
    shortKey: "cs",
    name: "cs.flag",
  },
  {
    key: "nl-NL",
    href: "/nl/",
    title: "Dutch (Netherlands)",
    shortKey: "nl",
    name: "nl.flag",
  },
  {
    key: "en-GB",
    href: "/en-GB/",
    title: "English (United Kingdom)",
    shortKey: "en-GB",
    name: "en-GB.flag",
  },
  {
    key: "en-US",
    href: "/",
    title: "English (United States)",
    shortKey: "en",
    name: "en.flag",
  },
  {
    key: "fi-FI",
    href: "/fi/",
    title: "Finnish (Finland)",
    shortKey: "fi",
    name: "fi.flag",
  },
  {
    key: "fr-FR",
    href: "/fr/",
    title: "French (France)",
    shortKey: "fr",
    name: "fr.flag",
  },
  {
    key: "de-DE",
    href: "/de/",
    title: "German (Germany)",
    shortKey: "de",
    name: "de.flag",
  },
  {
    key: "de-CH",
    href: "/de-CH/",
    title: "German (Switzerland)",
    shortKey: "de-CH",
    name: "de-CH.flag",
  },
  {
    key: "el-GR",
    href: "/el/",
    title: "Greek (Greece)",
    shortKey: "el",
    name: "el.flag",
  },
  {
    key: "it-IT",
    href: "/it/",
    title: "Italian (Italy)",
    shortKey: "it",
    name: "it.flag",
  },
  {
    key: "ja-JP",
    href: "/ja/",
    title: "Japanese (Japan)",
    shortKey: "ja",
    name: "ja.flag",
  },
  {
    key: "ko-KR",
    href: "/ko/",
    title: "Korean (Korea)",
    shortKey: "ko",
    name: "ko.flag",
  },
  {
    key: "lv-LV",
    href: "/lv/",
    title: "Latvian (Latvia)",
    shortKey: "lv",
    name: "lv.flag",
  },
  {
    key: "pl-PL",
    href: "/pl/",
    title: "Polish (Poland)",
    shortKey: "pl",
    name: "pl.flag",
  },
  {
    key: "pt-BR",
    href: "/pt-BR/",
    title: "Portuguese (Brazil)",
    shortKey: "pt-BR",
    name: "pt-BR.flag",
  },
  {
    key: "pt-PT",
    href: "/pt/",
    title: "Portuguese (Portugal)",
    shortKey: "pt",
    name: "pt.flag",
  },
  {
    key: "ru-RU",
    href: "/ru/",
    title: "Russian (Russia)",
    shortKey: "ru",
    name: "ru.flag",
  },
  {
    key: "sk-SK",
    href: "/sk/",
    title: "Slovak (Slovakia)",
    shortKey: "sk",
    name: "sk.flag",
  },
  {
    key: "sl-SI",
    href: "/sl/",
    title: "Slovenian (Slovenia)",
    shortKey: "sl",
    name: "sl.flag",
  },
  {
    key: "es-MX",
    href: "/es-MX/",
    title: "Spanish (Mexico)",
    shortKey: "es-MX",
    name: "es-MX.flag",
  },
  {
    key: "es-ES",
    href: "/es/",
    title: "Spanish (Spain)",
    shortKey: "es",
    name: "es.flag",
  },
  {
    key: "tr-TR",
    href: "/tr/",
    title: "Turkish (Turkey)",
    shortKey: "tr",
    name: "tr.flag",
  },
  {
    key: "uk-UA",
    href: "/uk/",
    title: "Ukrainian (Ukraine)",
    shortKey: "uk",
    name: "uk.flag",
  },
  {
    key: "vi-VN",
    href: "/vi/",
    title: "Vietnamese (Vietnam)",
    shortKey: "vi",
    name: "vi.flag",
  },
];
